#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear DNS cache.

alias clear-dns-cache="sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Empty the trash, the main HDD and on all mounted volumes,
# and clear Apple’s system logs to improve shell startup speed.

alias empty-trash="sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons.

alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false \
                            && killall Finder"

alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true \
                            && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show hidden files in Finder.

alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false \
                            && killall Finder"

alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true \
                            && killall Finder"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias localip="ipconfig getifaddr en1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup \
            && pip install --upgrade pip setuptools virtualenv virtualenvwrapper \
            && pip3 install --upgrade pip setuptools wheel \
            && npm install -g npm \
            && npm update -g \
            && sudo gem update --system \
            && sudo gem update"
